language: node_js
deploy:
  email: artkor@live.ru
  provider: npm
  api_key:
    secure: mab3qCgD8u/O4C15RQwSxxTeowrUkaM8DUMG7Zd7yTU62mmXgwZzipnifq52tEjN+CPF7gfQyCX6XxLC8NYf8C5o5fE8K7BaOVOnAkdeMn+xE7YImAOCguttVNbGhAHYC5I7RL8AvBvEYATHe5955TSttEohGTi2mo18iWST+/2lNHzEQmQgfXg7S3CosJkdTIDsTW6e7fnxVmgJ7k8G89EBMTtioPuNxA6HlBrTUcfzBCPnQJwBqd9Hw5xBvY2Tlo8rS5xOX2+2rXpZrxYW7DdomSh14YLtTpi9RiG1GovDbQLESaV3mYxPX5/JvKT7r4Z6RKWqqwjr+1osKu2J4GAWS7TRhh2YUKi+Sg63bwiOie3A2jJrKmqkh8cM9MOaGeSNcM9k72WVUd5yR3au86a10fui43yRky9XFgI3GiIowxweg7gQMFyJqI+vti19g5KfFBaKb5+BY0IxBHRhr2nzZIa5ZXtQPKllWcp7IKNRkNE3caVsqbX5CWBh1jLtaXY22rNpUdbq5kBO5R2Lf0v3dBtKxE77OnXctFHj1t2vJhxI0FikK+6vAGbPMew3NuI797xGk2apC/1Q5k0OhwJM1ilCo4+LRVMlL6JyDxYnbHt00kPgMnleUcz0WuUjhAlJZ9BuEW4c7LntE4WuvfXzt3E7j2nd9BZZRd982q0=
"  api_key": a78e6ffd-4da6-48ad-a73d-2b9ad9f8c9be
"  email": artkor@live.ru
"  provider": npm
